apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  replicas: {{ default 1 .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - image: msftgbb/data-api:latest
          imagePullPolicy: Always
          name: data-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: MONGODB_USER
              value: "dbuser"
            - name: MONGODB_PASSWORD
              value: "dbpassword"
            - name: MONGODB_IP
              value: "mongodb.hackfest.svc.cluster.local"
            - name: MONGODB_PORT
              value: "27017"                
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always