name: Container CI/CD
on: [push]
jobs:
  build:
    env:
      ACR_NAME: briaracr
      AKS_CLUSTER_NAME: briar-kubecon-01
      AKS_RG: aks
    runs-on: ubuntu-latest
    steps:
    
    # github Checkout
    - uses: actions/checkout@master

    # login to azure and build container image
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr build -t hackfest/flights-api:${{ github.sha }} -r $ACR_NAME --no-logs app/flights-api
        
    # set AKS context (https://github.com/Azure/aks-set-context)
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: ${{ AKS_RG }}
        cluster-name: ${{ AKS_CLUSTER_NAME }}
      id: login
    
    # install kubernetes CLI
    - uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      id: install
    
    # run kubernetes commands
    - run: kubectl get node 
