name: Container CI/CD
on: [push]
jobs:
  build:
    env:
      ACR_NAME: briaracr
      AKS_CLUSTER_NAME: briar-kubecon-01
      AKS_RG: aks
    runs-on: ubuntu-latest
    steps:
    
    # github Checkout
    - uses: actions/checkout@master

    # login to azure and build container image
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr build -t hackfest/flights-api:${{ github.sha }} -r $ACR_NAME --no-logs app/flights-api
        
    # set AKS context (https://github.com/Azure/aks-set-context)
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: ${{ env.AKS_RG }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      id: login
    
    # install kubernetes CLI
    - uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      id: install
    
    # trigger canary deploy with Flagger
    - run: kubectl -n hackfest set image deployment/flights-api flights-api=$ACR_NAME.azurecr.io/hackfest/flights-api:${{ github.sha }}
 
    # slack notify that pipeline completed
    - uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: kubecon2019
        SLACK_USERNAME: Github Actions
        SLACK_ICON: https://github.com/quintessence/slack-icons/blob/master/images/octocat-spock-slack-icon.png
        SLACK_TITLE: flights-api CI/CD workflow
        SLACK_MESSAGE: 'container image created and deployed as canary to AKS'

      
