name: Container CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # github Checkout
    - uses: actions/checkout@master

    # azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr list
        
    # set AKS context (https://github.com/Azure/aks-set-context)
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'aks'
        cluster-name: 'briar-kubecon-01'
      id: login
    
    # install kubernetes CLI
    - uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      id: install
    
    # run kubernetes commands
    - run: kubectl get node 
