name: Container Security Scan
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # slack notify: start pull_request workflow
    - uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: kubecon2019
        SLACK_USERNAME: Github Actions
      with:
        args: '`flights-api` container image security scan on `pull_request`'

    # github Checkout
    - uses: actions/checkout@v1

    # build test container image
    - run: docker build ./app/flights-api --file app/flights-api/Dockerfile --tag localbuild/testimage:latest

    # scan for vulnerabilities
    - uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/testimage:latest"
        dockerfile-path: "./app/flights-api/Dockerfile"
        fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

    # slack notify: complete pull_request workflow
    - uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: kubecon2019
        SLACK_USERNAME: Github Actions
      with:
        args: 'anchore container image scan complete'
